### ISSUE TITLE
Recognize swipe actions

### ISSUE THREAD

**Issue by MaxXxaM** [Mood-al/react-tabs-scrollable#18]
Hi guy! Good job, but I have some issue.
I'm implementing offset action by timer and can't call clearInterval when user swipe items by touchpad or scrolling it. Do you have some ideas how it implements?

**Comment by Mood-al** [comment]
Can you make a reproduction? I didnt understand what you want to do!

**Comment by MaxXxaM** [comment]
It will be so difficult. I'll try to explain it in words again. 
I use this module like info scroll tabs with photo and description content. I need automatic scroll tabs by timer. While client focus on it, make some actions like a swipe, I need stop timer.

**Comment by Mood-al** [comment]
If i understood you, you want to stop the timer when the click event on the content happens, right?

**Comment by MaxXxaM** [comment]
No, after swiping items on laptop touchpad.

**Comment by Mood-al** [comment]
Do you have the function that fires or workd when swipe event happens?

If yes then react-tabs-scrollable has nothing to do with your approach..
All you have to do is create a boolean state and check when that event happens set the state to true and stop the timer and viceverse.

**Comment by Mood-al** [comment]
Or you mean tabs scroll?? You putting all your content inside the tabs and you want to stop the timer when you scroll the tabs on touchpad?

**Comment by MaxXxaM** [comment]
> Or you mean tabs scroll?? You are putting all your content inside the tabs and you want to stop the timer when you scroll the tabs on touchpad?

Yes, exactly! Scroll tabs by swiping

**Comment by Mood-al** [comment]
Please see this example : https://codesandbox.io/s/work-with-ref-in-react-tabs-scrollable-to-add-events-p3n8c9
You have access to the tabsContainerRef and thus you can add any event you would like to add.

in Your case i added the `onwheel` event and it fires when you scroll by your mouse or trackpad wheel or touch.

Please notice that you have to add a `debounce` functionality to the event because it renders too much and that may affect on your app's performance.
