### ISSUE TITLE
Error with lazy loading: Cannot read properties of null (reading 'scrollWidth') 

### ISSUE THREAD

**Issue by Dron007** [Mood-al/react-tabs-scrollable#5]
There is error when I switch from one lazy loaded page to another one.

> TypeError
> Cannot read properties of null (reading 'scrollWidth')
> Object.eval [as current]
> https://qrgm4f.csb.app/node_modules/react-tabs-scrollable/dist/index.modern.js:347:76
> eval
> https://qrgm4f.csb.app/node_modules/react-tabs-scrollable/dist/index.modern.js:28:32
> ResizeObserver.eval
> https://qrgm4f.csb.app/node_modules/react-tabs-scrollable/dist/index.modern.js:417:7
> later
> https://qrgm4f.csb.app/node_modules/react-tabs-scrollable/dist/index.modern.js:132:12
> This screen is visible only in development. It will not appear if the app crashes in production.
> Open your browser’s developer console to further inspect this error.
> This error overlay is powered by `react-error-overlay` used in `create-react-app`.

Please see the [sandbox](https://codesandbox.io/s/react-tabs-scrollable-example-forked-qrgm4f).
Steps to reproduce:

1. Open Home page
2. Open Other page

I suppose it happens here https://github.com/Mood-al/react-tabs-scrollable/blob/main/src/components/Tabs/index.js#L207 because `tabsRef.current` is null so adding
```
if (!tabsRef.current) {
  return
}
```
before this line should help.

**Comment by Mood-al** [comment]
First, Thank you for the clean reproduction.

I think the problem is because of not checking the null ref as u showed 

 I was aware of it in my new package for the svelte community svelte-tabs-scrollable and I fixed it there but I was busy finalizing the svelte package and adding new features to it when I finish the documentation I will fix the bug in react-tabs-scrollable and I will new features to it that I added to svelte-tabs-scrollable 
If you want to see the new features please see this website under the section "new" https://svelte-tabs-scrollable.vercel.app/

**Comment by Dron007** [comment]
Thank you. Maybe you could add a hotfix just for this particular issue and later add new features cause it is a blocker now.

**Comment by Mood-al** [comment]
> Thank you. Maybe you could add a hotfix just for this particular issue and later add new features cause it is a blocker now.
> 
> P.S. Nice new feature. I was also thinking about adding custom CSS with `scroll-snap-align` attribute to similarly position tabs when scrolling with arrow buttons.

Okay let me see if I can add the edit tomorrow if I could work with the computer. 


About the features, you can submit a feature request and I will see if I can add them.
I was thinking to build it again and change the code to make it look similar to the svelte-tabs-scrollable so for now i will add just a patch to fix the problem and we can see that in new version

**Comment by Dron007** [comment]
@Mood-al Yes, that would be great. As for the new features the library currently satisfies all my needs but I'll think about it. Comparing to some others I tried I was impressed how this library uses animation, hooks and resize APIs. It works smoothly and reliably on resize but maybe I find something during work.

**Comment by Mood-al** [comment]
> @Mood-al Yes, that would be great. As for the new features the library currently satisfies all my needs but I'll think about it. Comparing to some others I tried I was impressed how this library uses animation, hooks, and resize APIs. It works smoothly and reliably on resize but maybe I find something during work.

Feel free to suggest any changes or new features.

I want to add a lot of changes in the code I want to get rid of the many useEffects and use just one with resize observer on both the container and the tab itself and i want to use onClick to move the selected into view now I'm using the state and i feel it adds more unnecessary rerenders i did this in my new package svelte-tabs-scrollable and it worked just fine so I'm going to apply this on the react one soon

Actually the reason why i built this is not finding any replacement to satisfy my need there was MUI scrollable component but u have to download the whole library just to use it and there was a weird bug in it when i use RTL mode in Windows devices so i built one that satisfy all my needs in the project that i was working on and that's why I built it

**Comment by Mood-al** [comment]
Hello, I couldn't update the package to fix the issue because I need to rebuild the whole compiling process since I'm using an outdate process.
So here is my workaround your issue 
https://codesandbox.io/s/react-tabs-scrollable-example-forked-jw5wkw?file=/src/App.js

I got the code for the DynamicLoader from here https://stackoverflow.com/questions/56887650/react-lazy-loaded-component-loosing-its-state-gets-unmounted

I hope this can help u ..

**Comment by Mood-al** [comment]
Btw, why are you using the settimeout inside the lazy load? 
It seems if u removed it with the Promise it works fine

**Comment by Dron007** [comment]
@Mood-al The sandobx code is simplified part of bigger codebase with Redux, Webpack and other libraries and lazy loading was used for code splitting, there are special comments for Webpack insdie "lazy(() => import(" to add files to separate bundle. I only could emulate it in sandbox with `setTimeout`.

Thank you for the workaround but when do you roughly plan to post a full-fledged fix? I am not sure I will be able to integrate this changes into my codebase. It may break something else. Probably I could just switch off lazy loading at all for some time. Is it possible to add to built file just a one-liner `if (!tabsRef.current)  return;` as a hotfix? I could try to do it in forked version if it is hard to do it in this repository.

**Comment by Dron007** [comment]
Also I have lines like this
```js
const SomePage = lazy(() => import(/* webpackChunkName: "admin" */'components/App/SomePage/Index'))
```
so it is simply impossible to use functions to generate import directives. I tend to just put patched `index.modern.js` locally disabling linter for it as a temporary easy solution.

**Comment by Mood-al** [comment]
> @Mood-al The sandobx code is simplified part of bigger codebase with Redux, Webpack and other libraries and lazy loading was used for code splitting, there are special comments for Webpack insdie "lazy(() => import(" to add files to separate bundle. I only could emulate it in sandbox with `setTimeout`.
> 
> Thank you for the workaround but when do you roughly plan to post a full-fledged fix? I am not sure I will be able to integrate these changes into my codebase. It may break something else. Probably I could just switch off lazy loading at all for some time. Is it possible to add to built file just a one-liner `if (!tabsRef.current)  return;` as a hotfix? I could try to do it in forked version if it is hard to do it in this repository.


I was going to tell you to open a PR to fix it.
But since there is an issue with the library that I'm using to compile the code it would be hard on u!
 I tried to fix it today but it seems it needs digging and since it's the library that I'm using to compile everything is an old library it would be hard to fdo that in my current situation 
But if you want you can open PR  and fix the issue the problem that i faced when i tried to update the code was with compiling the css file with the js bundle and since i dont have my old laptop that i built the project on i dont even remember how i did it in my last update!


Or if you want u can fork the repo and edit it as u want.

 hopefully soon i can fix it.

**Comment by Dron007** [comment]
I didn't have a chance to work with `microbundle` and create NPM modules so maybe I miss some point. This fix doesn't affect CSS. Is it possible to make a simple js fix, build js files keeping old CSS files from `/dist` (files from https://www.npmjs.com/package/react-tabs-scrollable?activeTab=explore), bump version in `package.json` etc. and publish updated version to NPM? I see that there is something wrong with CSS. `rts.css` in /dist differs from GitHub one. But it may be fixed separately and shouldn't interfere with this issue. Correct me if I am wrong.

**Comment by Mood-al** [comment]
Hey, I figured it out I moved the rts.css file manually to the generated dist folder.

I fixed the bug and update the the package please update the package to the last version 1.0.10

here is the sandbox with the fixed bug : https://codesandbox.io/s/react-tabs-scrollable-example-forked-me9twz?file=/src/App.js.

**Comment by Dron007** [comment]
@Mood-al Thank you! I tried it and it works fine for me now.

**Comment by Mood-al** [comment]
Hey,

I'm working now on v2 of react-tabs-scrollable and I opened this discussion for any feature request, so if there any features you would like to see please comment there.
https://github.com/Mood-al/react-tabs-scrollable/discussions/11#discussion-5067141
