### ISSUE TITLE
what is the best option for custom styling? 

### ISSUE THREAD

**Issue by jasan-s** [Mood-al/react-tabs-scrollable#9]
ended up using included css , now trying to override some syles for the tabs and the nav btns. 
curretnly used some !important to override stykes for tabs, however what the best option to override the nav btns styling? i'm was going to simply use the assigned class and add !important styles. was hoping to have a styles prop for nav bts and the tabs etc.

**Comment by Mood-al** [comment]
It's really doesn't matter you can use whatever you want and yes i was going to add style props to all elements inside the package but as you know I'm not able to develop the package due to the create-react-library package that i used to build this package and so far i couldnt find another library to help do that.


About adding !important you dont have to do that just rearrange the rts.css to the top level and put your custom style css file in the bottom so it can override the rts styles
